<?php

declare(strict_types=1);

// Pure settings serialization for the flash .cfg. No I/O here: wap_render_cfg()
// turns posted form fields into the KEY="value" body that BOTH consumers read -
// the webGui page (Unraid parse_plugin_cfg / parse_ini) and rc.preloadd's
// cfg_get (grep + strip-surrounding-quotes). Keeping this I/O-free is what makes
// it unit-testable by test/settings_test.php without a real flash disk or HTTP.

/**
 * Sanitize a free-text .cfg scalar. Both consumers put the value inside
 * double quotes, and NEITHER unescapes it: rc.preloadd's cfg_get strips one
 * surrounding quote pair and hands the raw bytes to toml_escape downstream, and
 * Unraid's ini parser treats a bare quote/newline as a syntax break. So the
 * robust policy is to REMOVE the characters that can break the KEY="value" line
 * rather than escape them (escaping would leave literal backslashes in the value
 * because the consumers never unescape). Control chars (newline/CR/tab/etc.)
 * are the real line-injection vector; double-quote and backslash never appear
 * legitimately in a server URL, comma-separated user list, or path-map, so
 * dropping them is lossless for real input and closes the injection surface.
 */
function wap_cfg_sanitize_str(string $v): string
{
    // Drop C0 controls (0x00-0x1F), DEL (0x7F), and the quote/backslash that
    // would terminate or corrupt the quoted scalar.
    $v = preg_replace('/[\x00-\x1F\x7F"\\\\]/', '', $v);

    return trim((string) $v);
}

/**
 * Coerce a posted numeric field to an int within [$min, $max], falling back to
 * $default when the value is non-numeric or out of range. Rendered unquoted
 * downstream, so a non-numeric value here could otherwise inject into the .cfg.
 */
function wap_cfg_clamp_int(mixed $v, int $min, int $max, int $default): int
{
    if (!\is_scalar($v) || !is_numeric((string) $v)) {
        return $default;
    }
    $n = (int) $v;
    if ($n < $min) {
        return $min;
    }
    if ($n > $max) {
        return $max;
    }

    return $n;
}

/**
 * Build the flash .cfg body from posted form fields. Only the fields the
 * settings form actually posts are emitted; every other engine default is left
 * to rc.preloadd's cfg_get fallbacks. The output is a well-formed KEY="value"
 * file safe for both the ini parser and cfg_get.
 *
 * @param array<string, mixed> $post the raw $_POST (or an equivalent map)
 */
function wap_render_cfg(array $post): string
{
    // SERVER_TYPE is constrained to the only adapter shipping in Phase 2; a
    // spoofed value can never select an unsupported server.
    $serverType = wap_cfg_sanitize_str((string) ($post['SERVER_TYPE'] ?? 'emby'));
    if ($serverType !== 'emby') {
        $serverType = 'emby';
    }

    $serverUrl = wap_cfg_sanitize_str((string) ($post['SERVER_URL'] ?? ''));
    if ($serverUrl === '') {
        $serverUrl = 'http://localhost:8096';
    }

    $users    = wap_cfg_sanitize_str((string) ($post['USERS'] ?? ''));
    $pathMaps = wap_cfg_sanitize_str((string) ($post['PATH_MAPS'] ?? ''));

    $ram      = wap_cfg_clamp_int($post['RAM_PERCENT'] ?? null, 1, 100, 50);
    $target   = wap_cfg_clamp_int($post['TARGET_SECONDS'] ?? null, 1, 86400, 20);
    $interval = wap_cfg_clamp_int($post['CRON_INTERVAL'] ?? null, 1, 59, 15);

    $lines = [
        '# GENERATED by the Watch-Aware Preloader settings page. Edit in the',
        '# webGui (Settings -> Watch-Aware Preloader); rewritten on every save.',
        \sprintf('SERVER_TYPE="%s"', $serverType),
        \sprintf('SERVER_URL="%s"', $serverUrl),
        \sprintf('USERS="%s"', $users),
        \sprintf('RAM_PERCENT="%d"', $ram),
        \sprintf('TARGET_SECONDS="%d"', $target),
        \sprintf('PATH_MAPS="%s"', $pathMaps),
        \sprintf('CRON_INTERVAL="%d"', $interval),
    ];

    return implode("\n", $lines) . "\n";
}
